### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucilapastore**

### CODE REVIEW

**Comment by wathigo** [comment]
**Reviewing...**

**Review by wathigo — CHANGES_REQUESTED** [review]
## Hi @lucilapastore 
### The clone looks great!
There just a few things we need to fix,
* Remove scrolling on the x-axis.
* Your code contains some errors, Upload your files to [w3 validator](https://validator.w3.org/#validate_by_upload) and correct all the errors.
* Remember to make use of [github flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) for your next project.
* The search input element is not where is appears to be see this 
https://www.loom.com/share/3941f903e5804826a9a1a8be13668f23
Please fix this.
* Remember to give this Pull Request a title and short summary of the accomplished tasks.
**After implementing the changes, submit another request for review**

_I loved that you made use of [semantic html](https://www.w3schools.com/html/html5_semantic_elements.asp) elements :)_

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . Almost done. However you still have some linter errors to fix. Kindly fix them and submit another code review form :pray:

**Review by Forison — COMMENTED** [review]
# pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
## hi @lucilapastore,
You are almost there🙂 
- #### **[REQUIRED]** README 🙂 
Your readme file is supposed to be descriptive enough(readme has to describe the project you have worked on in detail. It can include information on collaborators, the technology used, why the project was designed, how to access, etc... ).[readme](https://github.com/Forison/Using-Bootstrap)

- #### **[REQUIRED]** LINTERS 🙂 
Your linters are still not working the way they ought to. read this [article](https://github.com/microverseinc/linters-config#linters-config) 
> click the ```check``` tag in your GitHub GUI and try to address the issue raised by the linters

# Kindly make those changes and submit for review again🙂 🙂 🙂 
Happy coding🙂 🙂 🙂

**Review by Redvanisation — APPROVED** [review]
### Hello @lucilapastore ⭐️  

### _Nice work on this project, it seems that you have met all the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
